### ISSUE TITLE
Form & List Pack plugin broken in backend after upgrade (Seblod 3.16, plugin 1.6)

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#521]
After upgrade to 3.16, the Seblod Form & List pack plugin (new version 1.6) breaks the back-end with

Too few arguments to function plgCCK_FieldCck_List::_render(), 5 passed in /html/plugins/cck_field/cck_list/cck_list.php on line 212 and exactly 6 expected

[Seblod forum](https://www.seblod.com/community/forums/fields-plug-ins/3-16-errors-seblod-form-list-pack)

**Comment by sebastienheraud** [comment]
Hello Giuse,

A new 1.6.1 release has just been published to fix the regression.
Please have a try.

Thank you!
Saba

**Comment by Giuse69** [comment]
Solved, thanks!
